### ISSUE TITLE
Add possibility to overwrite repo_url and edit_uri for includes

### ISSUE THREAD

**Issue by claaslisowski** [spotify/mkdocs-monorepo-plugin#2]
Thanks for this plugin, it's great.

We like to use the edit button to jump directly to our git repo in edit mode.

However when using `!include` the path doesn't match any longer the one which is specified in `edit_uri` in the main mkdocs.yml.

It would be great to have the possibility to add repo_url and edit_uri for the included dirs so that the correct git repo and edit_uri links are generated.

**Comment by claaslisowski** [comment]
I didn't check the plugins wiki and noticed there is already a plugin which does exactly that.

[https://gitlab.com/paulrbr/mkdocs-edit-url](https://gitlab.com/paulrbr/mkdocs-edit-url)

**Comment by bih** [comment]
@claaslisowski Ah interesting, yes this is something we haven't easily figured out yet. We will take a look at that plugin and see if we can incorporate that functionality directly (given it's a small plugin)

**Comment by FredrikMeyer** [comment]
Is there any update on this? (or was it somehow possible to use the plugin mentioned above?) Thanks.

**Comment by marc0olo** [comment]
why is that issue closed? I am currently playing around with this plugin where I want to aggregate MkDocs of multiple repositories using submodule includes.

it's crucial for me to have the correct edit link for the respective submodule repo.

did anyone solve that problem?

does https://gitlab.com/paulrbr/mkdocs-edit-url really help with that or am I talking about another issue?

**Comment by jdoiro3** [comment]
I'm working on a slightly different plugin. In [mkdocs-multirepo-plugin](https://github.com/jdoiro3/mkdocs-multirepo-plugin), you can specify the edit_uri in the config for each repo or in repo's mkdocs.yml. The implementation is in the on_NAV event.
